'use strict';
const path = require('path');
const paths = require('../lib/paths');
const env = require('../lib/env');

function num(name, def) {
  const raw = env.get(name);
  if (raw === undefined) return def;
  const n = Number(raw);
  return Number.isFinite(n) && n >= 0 ? n : def;
}

// Every timing and timeout in one place; the env names are test hooks and operator overrides.
function loadConfig() {
  const sec = (name, def) => num(name, def) * 1000;
  return {
    heartbeatMs: Math.max(50, sec('PHASE1_HEARTBEAT_SEC', 20)),
    pageRetryPauseMs: sec('SCREEN_PAGE_RETRY_PAUSE_SEC', 120),
    settleMs: num('PHASE1_SETTLE_MS', 5000),
    unlockPauseMs: num('PHASE1_UNLOCK_PAUSE_MS', 1500),
    maxConsecutivePageErrors: Math.max(1, Math.floor(num('PHASE1_MAX_CONSECUTIVE_PAGE_ERRORS', 5))),
    incompleteMaxRuns: Math.max(1, Math.floor(num('PHASE1_INCOMPLETE_MAX_RUNS', 3))),
    unlockFailLimit: Math.max(1, Math.floor(num('PHASE1_UNLOCK_FAIL_LIMIT', 5))),
    dbFailLimit: Math.max(1, Math.floor(num('PHASE1_DB_FAIL_LIMIT', 3))),
    screenInputMode: env.get('SCREEN_INPUT_MODE', 'stdin') === 'file' ? 'file' : 'stdin',
    runTimestamp: env.get('PHASE1_RUN_TIMESTAMP') || '',
    timeoutMs: {
      lock: sec('PHASE1_LOCK_TIMEOUT_SEC', 30),
      credits: sec('PHASE1_CREDITS_TIMEOUT_SEC', 180),
      db: sec('PHASE1_DB_TIMEOUT_SEC', 60),
      screenBatch: sec('PHASE1_SCREEN_TIMEOUT_SEC', 1500),
      screenSingle: sec('PHASE1_SINGLE_TIMEOUT_SEC', 330),
      unlock: sec('PHASE1_UNLOCK_TIMEOUT_SEC', 180),
      handoff: sec('PHASE1_HANDOFF_TIMEOUT_SEC', 3900),
      login: sec('PHASE1_LOGIN_TIMEOUT_SEC', 600),
    },
    browserMs: { open: 90000, wait: 90000, eval: 60000, probe: 30000, url: 20000, stateSave: 60000 },
  };
}

const ENV_SCRIPT_PREFIX = 'PHASE1_SCRIPT_';

// Every setting this package reads, with its default, so docs/ENV.md can be generated by grep.
const DOCUMENTED_ENV = Object.freeze({
  PHASE1_HEARTBEAT_SEC: '20 (seconds between HEARTBEAT lines while the screener runs)',
  SCREEN_PAGE_RETRY_PAUSE_SEC: '120 (pause before re-trying a page after a screening failure)',
  SCREEN_INPUT_MODE: 'stdin (stdin|file: how candidates reach the screener)',
  PHASE1_SETTLE_MS: '5000 (sleep after a networkidle timeout)',
  PHASE1_UNLOCK_PAUSE_MS: '1500 (pause after each queued candidate)',
  PHASE1_MAX_CONSECUTIVE_PAGE_ERRORS: '5 (stop after this many consecutive failed pages)',
  PHASE1_INCOMPLETE_MAX_RUNS: '3 (early-ended runs of one search in a row before its territory is consumed anyway; counter in runtime/phase1-incomplete-runs.json)',
  PHASE1_UNLOCK_FAIL_LIMIT: '5 (consecutive unlock failures that stop the run as incomplete)',
  PHASE1_DB_FAIL_LIMIT: '3 (consecutive candidates-db.js write failures that stop the run as incomplete)',
  PHASE1_RUN_TIMESTAMP: 'unset (yyyy-MM-dd-HHmmss: resume that run and reload its queue checkpoint)',
  PHASE1_LOCK_TIMEOUT_SEC: '30',
  PHASE1_CREDITS_TIMEOUT_SEC: '180',
  PHASE1_DB_TIMEOUT_SEC: '60',
  PHASE1_SCREEN_TIMEOUT_SEC: '1500 (one batch call; a timeout counts as screening unavailable)',
  PHASE1_SINGLE_TIMEOUT_SEC: '330 (one post-unlock review)',
  PHASE1_UNLOCK_TIMEOUT_SEC: '180',
  PHASE1_HANDOFF_TIMEOUT_SEC: '3900 (Phase 2 / run-pipeline hand-off)',
  PHASE1_LOGIN_TIMEOUT_SEC: '600 (the one automatic re-login)',
  PHASE1_SCRIPT_NAME: 'unset (test hook: absolute path replacing scripts/<name>.js, e.g. PHASE1_SCRIPT_AI_REVIEW)',
  CATERER_SESSION_FILE: 'unset (overrides the saved browser session path)',
});

// candidates-db.js lives at the workspace root, every other script under scripts/.
function scriptPath(name) {
  const key = ENV_SCRIPT_PREFIX + name.toUpperCase().replace(/[^A-Z0-9]/g, '_');
  const override = env.get(key);
  if (override) return path.resolve(override);
  if (name === 'candidates-db') return path.join(paths.HOME, 'candidates-db.js');
  return path.join(paths.SCRIPTS, name + '.js');
}

module.exports = { loadConfig, scriptPath, ENV_SCRIPT_PREFIX, DOCUMENTED_ENV };
