'use strict';
// The rubric must be the legacy prompt VERBATIM (ASCII dashes only). The goldens in fixtures/ were
// generated by executing the legacy prompt and tier functions (read-only) and normalising the
// mojibake dash; tests compare the new builders against them.
const h = require('./helpers');
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const rubric = require(h.lib('screening/rubric'));
const tiers = require(h.lib('screening/tiers'));
const golden = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures', 'legacy-prompts.json'), 'utf8'));
const goldenTiers = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures', 'legacy-tiers.json'), 'utf8'));

test('batch prompt equals the legacy batch prompt for every tier (legacy tail)', () => {
  for (const [job, g] of Object.entries(golden.prompts)) {
    assert.equal(rubric.buildBatchPrompt(job, 'M1', 20, golden.candidates), g.batch, `job ${job}`);
  }
});

test('legacy tier function: identical outputs on the golden table incl. the Commis Chef quirk', () => {
  for (const [title, tier] of Object.entries(goldenTiers)) {
    assert.equal(tiers.getRoleTier(title, 'legacy'), tier, title);
  }
  assert.equal(tiers.getRoleTier('Commis Chef', 'legacy'), 2, 'legacy quirk preserved');
  assert.equal(tiers.getRoleTier('Sous-Chef', 'legacy'), 2);
  assert.equal(tiers.getRoleTier('Catering Assistant', 'legacy'), 0);
  assert.equal(tiers.getRoleTier('', 'legacy'), 0);
  assert.equal(tiers.getRoleTier(undefined, 'legacy'), 0);
});

test('SCREEN_TIER_MODE=fixed changes ONLY commis titles (to tier 1)', () => {
  for (const [title, tier] of Object.entries(goldenTiers)) {
    const fixed = tiers.getRoleTier(title, 'fixed');
    if (/commis/i.test(title)) assert.equal(fixed, 1, title);
    else assert.equal(fixed, tier, title);
  }
});

test('prompt note selection follows the search tier: <=1 entry-level limit, >=2 over-qualification is fine', () => {
  const entry = rubric.buildOverqualNote(0);
  assert.equal(rubric.buildOverqualNote(1), entry);
  assert.match(entry, /OVER-QUALIFICATION LIMIT for entry-level roles/);
  for (const t of [2, 3, 4]) assert.match(rubric.buildOverqualNote(t), /is NOT a reason to reject/);
  // tier 0 (unknown, e.g. Waiter) gets the entry-level note; Commis Chef (legacy tier 2) the lenient one
  assert.match(rubric.buildBatchPrompt('Waiter', '', 20, []), /OVER-QUALIFICATION LIMIT/);
  assert.match(rubric.buildBatchPrompt('Commis Chef', '', 20, []), /is NOT a reason to reject/);
  assert.match(rubric.buildBatchPrompt('Commis Chef', '', 20, [], { tierMode: 'fixed' }), /OVER-QUALIFICATION LIMIT/);
});

test('D2: the single prompt shares the batch rules block (incl. the Commis-for-Chef exception)', () => {
  for (const job of ['Chef', 'Head Chef', 'Kitchen Porter']) {
    const body = rubric.buildRubricBody(job);
    assert.ok(rubric.buildBatchPrompt(job, 'M1', 20, golden.candidates).includes(body));
    assert.ok(rubric.buildSinglePrompt(job, 'Sous Chef', 'snippet').includes(body));
  }
  assert.match(rubric.buildSinglePrompt('Chef', 'Cook', 's'), /a Commis Chef for a generic 'Chef' search = APPROVE/);
  // the legacy single prompt lacked that sentence
  assert.ok(!golden.prompts.Chef.single.includes("a Commis Chef for a generic 'Chef' search = APPROVE"));
});

test('the legacy tails are untouched; the structured tails add reason codes', () => {
  assert.ok(rubric.buildBatchPrompt('Chef', '', 20, []).endsWith('[{"id":"...","approved":true,"reason":"one line, max 15 words"},...]'));
  assert.ok(rubric.buildSinglePrompt('Chef', 'x', 'y').endsWith('{"approved":true,"reason":"one line, max 15 words"}'));
  const obj = rubric.buildBatchPrompt('Chef', 'M1', 20, [{ id: 'a', snippet: 's' }], { output: 'object' });
  assert.match(obj, /reject_foh_only - /);
  assert.match(obj, /"reasonCode":"\.\.\."/);
});

test('rubric text is ASCII only; stale-profile clause is off by default and opt-in', () => {
  const all = rubric.buildBatchPrompt('Chef', 'M1', 20, golden.candidates, { output: 'object' }) + rubric.buildSinglePrompt('Chef', 't', 's', { output: 'object' }) + rubric.SYSTEM_MESSAGE;
  assert.ok(!/[^\x00-\x7f]/.test(all));
  assert.ok(!/out of date/.test(rubric.buildRubricBody('Chef')));
  assert.match(rubric.buildRubricBody('Chef', { staleProfileClause: true }), /out of date/);
  assert.notEqual(rubric.rubricHash('Chef', {}), rubric.rubricHash('Chef', { staleProfileClause: true }));
});

test('schema is strict: additionalProperties false, every property required, no numeric ranges', () => {
  const check = s => {
    assert.equal(s.additionalProperties, false);
    assert.deepEqual([...s.required].sort(), Object.keys(s.properties).sort());
    for (const p of Object.values(s.properties)) {
      assert.ok(!('minimum' in p) && !('maximum' in p));
    }
  };
  check(rubric.DECISION_SCHEMA);
  assert.equal(rubric.DECISION_SCHEMA.properties.approved.type, 'boolean');
});

test('candidate-side tier: commis before generic chef, hyphens tolerated', () => {
  assert.equal(tiers.candidateTier('Commis Chef'), 1);
  assert.equal(tiers.candidateTier('Sous-Chef'), 3);
  assert.equal(tiers.candidateTier('Head Chef'), 4);
  assert.equal(tiers.candidateTier('Chef de Partie'), 2);
  assert.equal(tiers.candidateTier('Kitchen Porter'), 1);
  assert.equal(tiers.candidateTier('Waiter'), 0);
  assert.equal(tiers.recentRoleTitle('12. X Chef | Leeds Recent experience Other CV snippets Sous Chef Jan 2020 - Current Hotel'), 'Sous Chef');
  assert.equal(tiers.recentRoleTitle('Other CV snippets Not available'), '');
  assert.equal(tiers.headlineOf('12. Alex Head Chef | Leeds, LS1'), 'Alex Head Chef');
});

test('opt-in variant insufficientEvidence=lenient replaces ONLY the no-history bullet; the default is the legacy text', () => {
  const legacy = rubric.buildRubricBody('Chef', {});
  const lenient = rubric.buildRubricBody('Chef', { insufficientEvidence: 'lenient' });
  assert.match(legacy, /- No meaningful professional background or relevant history is visible/);
  assert.ok(!/very little detail/.test(legacy));
  assert.match(lenient, /a card with very little detail is NOT enough to reject/);
  assert.ok(!/No meaningful professional background/.test(lenient));
  assert.equal(legacy.replace('- No meaningful professional background or relevant history is visible', '@@'), lenient.replace(/- The visible background shows nothing relevant[^\n]*/, '@@'));
  assert.equal(rubric.variantOf({}), 'legacy-1');
  assert.equal(rubric.variantOf({ insufficientEvidence: 'lenient', staleProfileClause: true }), 'legacy-1+lenient+stale');
  assert.ok(!/[^\x00-\x7f]/.test(lenient));
});
